### ISSUE TITLE
PTU could not be assigned. Query is part of a graph component of size 1

### ISSUE THREAD

**Issue by sunctx** [santirdnd/COPLA_initial_concept#1]
Dear santirdnd,
Congratulations for your nice paper on PTU concept, and glad to see the PTU assignment tool COPLA has come out.
I have installed COPLA and the dependences (though not directly installed based on the given commend lines, some errors occurred when doing so. I have managed to installed the dependences one by one via conda).
When testing with the given fna file (`NZ_CP028167.1.fna`, `NZ_CP028329.1.fna`), COPLA didn't output same results as indicated in `./test/NZ_CP028167.1_results/`, instead write in `*.fna.ptu_prediction.tsv` "PTU could not be assigned. Query is part of a graph component of size 1".
I tried some other circular plasmid sequences, which all returned the seem error "PTU could not be assigned. Query ..."
########

following are the packages in the copla and macsyfinder environment
********************************************************************************************************************************
(copla-env) [cvmsct@mu01 ~]$ conda list
# packages in environment at /disk1/cau/cvmsct/miniconda3/envs/copla-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
at-spi2-atk               2.32.0               h1369247_0    pkgw-forge
at-spi2-core              2.32.1               h1369247_0    pkgw-forge
atk                       2.36.0                        3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
atk-1.0                   2.36.0               haf93ef1_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
biopython                 1.78             py38h1e0a361_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
blast                     2.9.0           pl526he19e7b1_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
boost                     1.72.0           py38h1e42940_1    conda-forge
boost-cpp                 1.72.0               h9359b55_3    conda-forge
bzip2                     1.0.8                h516909a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
c-ares                    1.11.0               h470a237_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cairomm                   1.12.2                        2    conda-forge
cairomm-1.0               1.12.2               h0069156_2    conda-forge
certifi                   2020.6.20        py38h924ce5b_2    conda-forge
cgecore                   1.5.5              pyh864c0ab_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
curl                      7.71.1               he644dc0_8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
entrez-direct             13.9            pl526h375a9b1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
epoxy                     1.5.3                h516909a_0    pkgw-forge
expat                     2.2.9                he1b5a44_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fontconfig                2.13.1            h1056068_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
freetype                  2.10.4               he06d7ca_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fribidi                   1.0.10               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gdk-pixbuf                2.36.12           h3f25603_1005    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gettext                   0.19.8.1          hf34092f_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
glib                      2.58.3          py38h73cb85d_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gmp                       6.2.0                he1b5a44_3    conda-forge
gobject-introspection     1.66.1           py38h03d966d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
graph-tool                2.33             py38hed06623_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gtk3                      3.24.9               h72f7a92_0    pkgw-forge
harfbuzz                  2.7.2                hee91db6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
hmmer                     3.3.1                he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
icu                       67.1                 he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jpeg                      9d                   h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
kiwisolver                1.2.0            py38hbf85e49_1    conda-forge
kma                       1.3.6                hed695b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
krb5                      1.17.1               hfafb76e_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libblas                   3.9.0                2_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcblas                  3.9.0                2_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libcurl                   7.71.1               hcdd3856_8    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libedit                   3.1.20191231         he28a2e2_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libev                     4.33                 h516909a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.2.1             he1b5a44_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran5              9.3.0               he4bcb1c_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp                   9.3.0               h5dbcf3e_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                2_openblas    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnghttp2                1.41.0               hab1572f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.37               hed695b0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
librsvg                   2.50.1               h33a7fed_0    conda-forge
libssh2                   1.9.0                hab1572f_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.1.0                hc7e4089_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.32.1            h14c3975_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.1.0                h516909a_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcb                    1.13              h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxkbcommon              0.8.4                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.9.10               h68273f3_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lz4-c                     1.9.2                he1b5a44_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib-base           3.3.2            py38h4d1ce4f_1    conda-forge
ncurses                   6.2                  he1b5a44_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.19.2           py38hf89b668_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.1.3            py38hddd6c8b_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pango                     1.42.4               h7062337_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pcre                      8.44                 he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
perl                      5.26.2            h516909a_1006    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
perl-app-cpanminus        1.7044                  pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-archive-tar          2.32                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-base                 2.23                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-business-isbn        3.004                   pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-business-isbn-data   20140910.003            pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-carp                 1.38                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-common-sense         3.74                    pl526_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-constant             1.33                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-data-dumper          2.173                   pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-digest-hmac          1.03                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-digest-md5           2.55                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-encode               2.88                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-encode-locale        1.05                    pl526_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-exporter             5.72                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-exporter-tiny        1.002001                pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-extutils-makemaker   7.36                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-file-listing         6.04                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-file-path            2.16                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-file-temp            0.2304                  pl526_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-html-parser          3.72            pl526h6bb024c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-html-tagset          3.20                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-html-tree            5.07                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-http-cookies         6.04                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-http-daemon          6.01                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-http-date            6.02                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-http-message         6.18                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-http-negotiate       6.01                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-io-compress          2.087           pl526he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-io-html              1.001                   pl526_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-io-socket-ssl        2.066                   pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-io-zlib              1.10                    pl526_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-json                 4.02                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-json-xs              2.34            pl526h6bb024c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-libwww-perl          6.39                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-list-moreutils       0.428                   pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-list-moreutils-xs    0.428                   pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-lwp-mediatypes       6.04                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-lwp-protocol-https   6.07                    pl526_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-mime-base64          3.15                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-mozilla-ca           20180117                pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-net-http             6.19                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-ntlm                 1.09                    pl526_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-parent               0.236                   pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-pathtools            3.75            pl526h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-socket               2.027                   pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-storable             3.15            pl526h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-test-requiresinternet 0.05                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-time-local           1.28                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-try-tiny             0.30                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-types-serialiser     1.0                     pl526_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-uri                  1.76                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-www-robotrules       6.02                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-namespacesupport 1.12                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-sax              1.02                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-sax-base         1.09                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-sax-expat        0.51                    pl526_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xml-simple           2.25                    pl526_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
perl-xsloader             0.24                    pl526_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pillow                    8.0.1            py38h9776b28_0    conda-forge
pip                       20.2.4                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pixman                    0.38.0            h516909a_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
plasmidfinder             2.1.1                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
prodigal                  2.6.3                h516909a_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pthread-stubs             0.4               h14c3975_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pycairo                   1.20.0           py38h323dad1_1    conda-forge
pygobject                 3.38.0           py38h2faf24e_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.8.0                h357f687_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python_abi                3.8                      1_cp38    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytz                      2020.1             pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
readline                  8.0                  he28a2e2_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scipy                     1.5.2            py38hd9480d8_2    conda-forge
setuptools                49.6.0           py38h924ce5b_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sigcpp-2.0                2.10.3               he1b5a44_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sparsehash                2.0.3             hf484d3e_1000    conda-forge
sqlite                    3.33.0               h4cf870e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.8.7              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tk                        8.6.10               hed695b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tornado                   6.0.4            py38h1e0a361_2    conda-forge
tzdata                    2020d                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wayland                   1.17.0               hfcf6f83_0    pkgw-forge
wheel                     0.35.1             pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-fixesproto           5.0               h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libice               1.0.10               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libsm                1.2.3             h84519dc_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libx11               1.6.12               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxau               1.0.9                h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxcursor           1.2.0                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxext              1.3.4                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxi                1.7.10               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxinerama          1.1.4             hf484d3e_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxrandr            1.5.2                h516909a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxrender           0.9.10            h516909a_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxtst              1.2.3             h516909a_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-randrproto           1.5.0             h516909a_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-recordproto          1.14.2            h516909a_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xproto               7.0.31            h14c3975_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.5                h516909a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zlib                      1.2.11            h516909a_1010    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zstd                      1.4.5                h6597ccf_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
********************************************************************************************************************************

********************************************************************************************************************************
(macsyfinder-env) [cvmsct@mu01 ~]$ conda list
# packages in environment at /disk1/cau/cvmsct/miniconda3/envs/macsyfinder-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blast                     2.9.0           pl526he19e7b1_7    bioconda
boost                     1.68.0          py27h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
entrez-direct             13.9            pl526h375a9b1_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             h71b1129_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hmmer                     3.2.1                he1b5a44_2    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.6                h6e990d7_6    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
macsyfinder               1.0.5                    pypi_0    pypi
ncurses                   6.2                  he1b5a44_2    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
numpy                     1.15.4          py27h8b7e671_1001    conda-forge
openblas                  0.3.6                h6e990d7_6    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44            pl526h4e0c4b3_7    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
*********************************************************************************************************
one of the outputs：
<img width="414" alt="WX20201028-220900@2x" src="https://user-images.githubusercontent.com/60634995/97447169-3ddc2f00-196a-11eb-9293-a4f2ed2705cc.png">

**Comment by santirdnd** [comment]
Hello sunctx, sorry for your difficulties. Right now the code has too many rough edges, with some parts adapted to my development environment. I have a backlog of changes that I want to commit soon, maybe some of them will help

PS: I want to get rid of having the sequences database included into the repository, it is not future proof. Don't be surprised if I restart the repository. It's not fancy but I don't want to spend too much time on it. I really didn't expect anyone to be interested in this project already at this point

Best regards,
    Santiago

**Comment by sunctx** [comment]
Dear santirdnd,
Thanks for your kind response.
I have made it, COPLA has run correctly on the test fna files.

**************
#1#  Instead using `copla.environment.yml`, I have installed `copla.spec-file.txt` while developing COPLA.
The install of `gtk3` often returns with error "an error occurred when installing gtk3 ...."
#2# Instead install COPLA on a remote server cluster, I install it on a local linux server, which runs correctly.
The former errors in "Gdk-CRITICAL **: 14:55:37.289: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed".
**************
COPLA is fancy, thanks for your effort.
Chengtao
